name: Report bug PowerRequestWrapper
description: Report an issue with PowerRequestWrapper
body:
  - type: markdown
    attributes:
      value: |
        This issue form is for reporting bugs only!
  - type: textarea
    validations:
      required: true
    attributes:
      label: The problem
      description: |
        Please give a clear and concise description of the issue you are experiencing here, 
        to communicate to the maintainers. Tell us what you were trying to do and what happened.
  - type: textarea
    validations:
      required: true
    attributes:
      label: How to reproduce
      description: |
        Describe the least amount of steps possible to reproduce your error
  - type: textarea
    attributes:
      label: Additional information
      description: |
        If you have any additional information for us. Use the field below.
